-- Initial PostgreSQL schema. This application has not been deployed.
-- Publication days are DATE, binary attachments BYTEA and flags BOOLEAN.
-- API/evidence timestamps retain canonical UTC RFC3339 text, token times epoch seconds.

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    sort_order BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    reference_number TEXT,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    issuer TEXT,
    description TEXT,
    published_on DATE NOT NULL,
    withdraw_on DATE,
    withdrawn_at TEXT,
    retain_attachments BOOLEAN NOT NULL DEFAULT FALSE,
    status TEXT NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'scheduled', 'published', 'withdrawn', 'archived')),
    created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"')),
    updated_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"')),
    review_json TEXT NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(review_json::jsonb) IS NOT NULL),
    published_at TEXT,
    CHECK (withdraw_on IS NULL OR withdraw_on >= published_on)
);

CREATE TABLE administrators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE CHECK (email = lower(email)),
    password_hash TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE sessions (
    token_hash TEXT PRIMARY KEY,
    csrf_hash TEXT NOT NULL,
    administrator_id BIGINT NOT NULL REFERENCES administrators(id),
    expires_at BIGINT NOT NULL
);

CREATE TABLE rate_limits (
    key TEXT PRIMARY KEY,
    window_started_at BIGINT NOT NULL,
    count BIGINT NOT NULL
);

CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
    created_at TEXT NOT NULL,
    published_at TEXT
);

CREATE TABLE attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id BIGINT REFERENCES notices(id),
    document_id BIGINT REFERENCES documents(id),
    name TEXT NOT NULL,
    storage_path TEXT NOT NULL DEFAULT '',
    content_type TEXT NOT NULL,
    size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
    sort_order BIGINT NOT NULL DEFAULT 0,
    removed_at TEXT,
    data BYTEA,
    sha256 TEXT,
    CHECK ((notice_id IS NOT NULL) != (document_id IS NOT NULL)),
    CHECK (removed_at IS NULL OR data IS NULL)
);

CREATE TABLE pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    published BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TEXT NOT NULL
);

CREATE TABLE subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE CHECK (email = lower(email)),
    verified_at BIGINT,
    unsubscribed_at BIGINT,
    retention_started_at BIGINT NOT NULL
);

CREATE TABLE consent_notices (
    fingerprint TEXT PRIMARY KEY,
    version TEXT NOT NULL,
    consent_text TEXT NOT NULL,
    privacy_json TEXT NOT NULL
);

CREATE TABLE subscription_consents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscriber_id BIGINT NOT NULL REFERENCES subscribers(id) ON DELETE CASCADE,
    notice_fingerprint TEXT NOT NULL REFERENCES consent_notices(fingerprint),
    requested_at BIGINT NOT NULL,
    confirmed_at BIGINT,
    withdrawn_at BIGINT,
    superseded_at BIGINT,
    CHECK (confirmed_at IS NULL OR confirmed_at >= requested_at),
    CHECK (withdrawn_at IS NULL OR withdrawn_at >= requested_at)
);

CREATE TABLE subscription_tokens (
    hash TEXT PRIMARY KEY,
    subscriber_id BIGINT NOT NULL REFERENCES subscribers(id) ON DELETE CASCADE,
    purpose TEXT NOT NULL CHECK (purpose IN ('verification', 'unsubscribe')),
    expires_at BIGINT NOT NULL,
    consent_id BIGINT REFERENCES subscription_consents(id) ON DELETE CASCADE
);

CREATE TABLE mail_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscriber_id BIGINT NOT NULL REFERENCES subscribers(id) ON DELETE CASCADE,
    purpose TEXT NOT NULL CHECK (purpose IN ('verification', 'document')),
    deduplication_key TEXT UNIQUE,
    subject TEXT NOT NULL,
    body TEXT,
    attempts BIGINT NOT NULL DEFAULT 0,
    next_attempt_at BIGINT NOT NULL,
    locked_until BIGINT NOT NULL DEFAULT 0,
    lock_token TEXT,
    sent_at BIGINT,
    cancelled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at BIGINT NOT NULL,
    consent_id BIGINT REFERENCES subscription_consents(id) ON DELETE CASCADE
);

CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"')),
    actor_id BIGINT,
    operation TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id BIGINT,
    details TEXT,
    ip_address TEXT
);

CREATE TABLE notice_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id BIGINT NOT NULL REFERENCES notices(id),
    occurred_at TEXT NOT NULL,
    actor_id BIGINT REFERENCES administrators(id),
    kind TEXT NOT NULL,
    payload TEXT NOT NULL CHECK (jsonb_typeof(payload::jsonb) IS NOT NULL),
    sha256 TEXT NOT NULL
);

CREATE TABLE privacy_maintenance (
    id BIGINT PRIMARY KEY CHECK (id=1),
    audit_delete_before TEXT,
    notice_delete_before TEXT
);

CREATE INDEX notices_by_status ON notices(status, published_on DESC);
CREATE INDEX notices_due_for_withdrawal ON notices(withdraw_on)
    WHERE withdrawn_at IS NULL AND withdraw_on IS NOT NULL;
CREATE INDEX sessions_by_expiry ON sessions(expires_at);
CREATE INDEX attachments_by_notice ON attachments(notice_id, sort_order);
CREATE INDEX attachments_by_document ON attachments(document_id, sort_order);
CREATE INDEX subscription_tokens_by_expiry ON subscription_tokens(expires_at);
CREATE INDEX mail_queue_pending ON mail_queue(next_attempt_at, locked_until)
    WHERE sent_at IS NULL AND cancelled=FALSE;
CREATE INDEX audit_log_by_time ON audit_log(occurred_at DESC);
CREATE INDEX subscription_consents_by_subscriber ON subscription_consents(subscriber_id, requested_at);
CREATE UNIQUE INDEX subscription_consents_one_active ON subscription_consents(subscriber_id)
    WHERE withdrawn_at IS NULL AND superseded_at IS NULL;
CREATE INDEX notice_events_by_notice ON notice_events(notice_id,id);

INSERT INTO privacy_maintenance(id) VALUES (1);
INSERT INTO categories(name,sort_order) VALUES
    ('Veřejná vyhláška',10),('Záměr obce',20),('Zastupitelstvo',30),
    ('Rozpočet',40),('Volby',50),('Dražba',60),('Ostatní',99);

CREATE FUNCTION reject_protected_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'protected record is immutable: %', TG_TABLE_NAME;
END;
$$;
CREATE TRIGGER audit_log_prevent_update BEFORE UPDATE ON audit_log FOR EACH ROW EXECUTE FUNCTION reject_protected_change();
CREATE TRIGGER audit_log_prevent_truncate BEFORE TRUNCATE ON audit_log FOR EACH STATEMENT EXECUTE FUNCTION reject_protected_change();
CREATE TRIGGER notices_preserve_record BEFORE DELETE ON notices FOR EACH ROW EXECUTE FUNCTION reject_protected_change();
CREATE TRIGGER notices_prevent_truncate BEFORE TRUNCATE ON notices FOR EACH STATEMENT EXECUTE FUNCTION reject_protected_change();
CREATE TRIGGER attachments_preserve_metadata BEFORE DELETE ON attachments FOR EACH ROW EXECUTE FUNCTION reject_protected_change();
CREATE TRIGGER attachments_prevent_truncate BEFORE TRUNCATE ON attachments FOR EACH STATEMENT EXECUTE FUNCTION reject_protected_change();
CREATE TRIGGER consent_notices_immutable BEFORE UPDATE ON consent_notices FOR EACH ROW EXECUTE FUNCTION reject_protected_change();
CREATE TRIGGER notice_events_no_update BEFORE UPDATE ON notice_events FOR EACH ROW EXECUTE FUNCTION reject_protected_change();
CREATE TRIGGER notice_events_no_truncate BEFORE TRUNCATE ON notice_events FOR EACH STATEMENT EXECUTE FUNCTION reject_protected_change();

CREATE FUNCTION protect_consent_evidence() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.subscriber_id IS DISTINCT FROM OLD.subscriber_id
        OR NEW.notice_fingerprint IS DISTINCT FROM OLD.notice_fingerprint
        OR NEW.requested_at IS DISTINCT FROM OLD.requested_at
        OR (OLD.confirmed_at IS NOT NULL AND NEW.confirmed_at IS DISTINCT FROM OLD.confirmed_at)
        OR (OLD.withdrawn_at IS NOT NULL AND NEW.withdrawn_at IS DISTINCT FROM OLD.withdrawn_at)
        OR (OLD.superseded_at IS NOT NULL AND NEW.superseded_at IS DISTINCT FROM OLD.superseded_at)
    THEN RAISE EXCEPTION 'consent evidence is immutable'; END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER subscription_consents_preserve_evidence BEFORE UPDATE ON subscription_consents FOR EACH ROW EXECUTE FUNCTION protect_consent_evidence();

CREATE FUNCTION protect_audit_retention() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM privacy_maintenance WHERE id=1 AND OLD.occurred_at<audit_delete_before)
    THEN RAISE EXCEPTION 'audit log is append only during retention'; END IF;
    RETURN OLD;
END;
$$;
CREATE TRIGGER audit_log_prevent_delete BEFORE DELETE ON audit_log FOR EACH ROW EXECUTE FUNCTION protect_audit_retention();

CREATE FUNCTION protect_notice_retention() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM privacy_maintenance p JOIN notices n ON n.id=OLD.notice_id
        WHERE p.id=1 AND OLD.occurred_at<p.notice_delete_before
        AND n.status IN ('archived','withdrawn') AND n.withdrawn_at<p.notice_delete_before
    ) THEN RAISE EXCEPTION 'publication evidence is protected during retention'; END IF;
    RETURN OLD;
END;
$$;
CREATE TRIGGER notice_events_no_delete BEFORE DELETE ON notice_events FOR EACH ROW EXECUTE FUNCTION protect_notice_retention();
