CREATE TABLE password_resets (
    hash TEXT PRIMARY KEY,
    administrator_id BIGINT NOT NULL REFERENCES administrators(id) ON DELETE CASCADE,
    expires_at BIGINT NOT NULL,
    used_at BIGINT
);
CREATE INDEX password_resets_by_account ON password_resets(administrator_id);
CREATE TABLE recovery_mail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    administrator_id BIGINT NOT NULL REFERENCES administrators(id),
    token_hash TEXT REFERENCES password_resets(hash) ON DELETE SET NULL,
    body TEXT,
    created_at BIGINT NOT NULL,
    next_attempt_at BIGINT NOT NULL,
    attempts BIGINT NOT NULL DEFAULT 0,
    lock_token TEXT,
    locked_until BIGINT NOT NULL DEFAULT 0,
    sent_at BIGINT,
    delivery_expired_at BIGINT,
    cancelled BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX recovery_mail_pending ON recovery_mail(next_attempt_at, locked_until)
    WHERE sent_at IS NULL AND cancelled=FALSE;
