ALTER TABLE pages ADD COLUMN version BIGINT NOT NULL DEFAULT 1 CHECK (version>0);
CREATE TABLE page_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id BIGINT NOT NULL REFERENCES pages(id),
    version BIGINT NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    slug TEXT NOT NULL,
    published BOOLEAN NOT NULL,
    saved_at TEXT NOT NULL,
    actor_id BIGINT REFERENCES administrators(id),
    UNIQUE(page_id,version)
);
INSERT INTO page_revisions(page_id,version,title,content,slug,published,saved_at)
    SELECT id,version,title,content,slug,published,updated_at FROM pages;
CREATE TRIGGER page_revisions_no_update BEFORE UPDATE ON page_revisions FOR EACH ROW EXECUTE FUNCTION reject_protected_change();
CREATE TRIGGER page_revisions_no_delete BEFORE DELETE ON page_revisions FOR EACH ROW EXECUTE FUNCTION reject_protected_change();
CREATE TRIGGER page_revisions_no_truncate BEFORE TRUNCATE ON page_revisions FOR EACH STATEMENT EXECUTE FUNCTION reject_protected_change();

CREATE TABLE navigation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL,
    path TEXT NOT NULL,
    sort_order BIGINT NOT NULL DEFAULT 0,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 1 CHECK (version>0)
);
INSERT INTO navigation_items(label,path,sort_order) VALUES
    ('Přehled','/',10),('Úřední deska','/uredni-deska',20),('Dokumenty','/dokumenty',30),
    ('Obec a úřad','/obec',40);
ALTER TABLE categories ADD COLUMN version BIGINT NOT NULL DEFAULT 1 CHECK (version>0);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    location TEXT NOT NULL DEFAULT '',
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    published BOOLEAN NOT NULL DEFAULT FALSE,
    cancelled BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 1 CHECK (version>0),
    updated_at TEXT NOT NULL,
    CHECK (ends_at>=starts_at)
);
CREATE INDEX events_public_by_time ON events(starts_at,id) WHERE published=TRUE;
