CREATE TABLE page_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id BIGINT NOT NULL REFERENCES pages(id),
    name TEXT NOT NULL,
    content_type TEXT NOT NULL CHECK (content_type IN ('image/png','image/jpeg','image/webp','image/gif')),
    size_bytes BIGINT NOT NULL CHECK (size_bytes BETWEEN 1 AND 10485760),
    width INTEGER NOT NULL CHECK (width > 0),
    height INTEGER NOT NULL CHECK (height > 0),
    data BYTEA NOT NULL,
    sha256 TEXT NOT NULL,
    created_at TEXT NOT NULL,
    actor_id BIGINT REFERENCES administrators(id)
);
CREATE INDEX page_images_by_page ON page_images(page_id, id);
