-- Imports snapshot recipients atomically with the first public appearance.
-- Existing public records are deliberately not backfilled.
CREATE TABLE publication_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id BIGINT REFERENCES notices(id) ON DELETE CASCADE,
    document_id BIGINT REFERENCES documents(id) ON DELETE CASCADE,
    subscriber_id BIGINT NOT NULL REFERENCES subscribers(id) ON DELETE CASCADE,
    consent_id BIGINT NOT NULL REFERENCES subscription_consents(id) ON DELETE CASCADE,
    created_at BIGINT NOT NULL,
    CHECK ((notice_id IS NOT NULL) <> (document_id IS NOT NULL)),
    UNIQUE (notice_id, subscriber_id),
    UNIQUE (document_id, subscriber_id)
);
